# Generated by Django 3.1.4 on 2020-12-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='TEST de prueba de la ddescripcion del producto'),
            preserve_default=False,
        ),
    ]
