# Generated by Django 3.1.4 on 2020-12-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='amount',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
